### ISSUE TITLE
Exit creation and music issue

### ISSUE THREAD

**Issue by shadowpates** [chrisnorman7/earwax#21]
Hi,
I can't create an exit with earwax story. And, If I want to pick an object the ambiance stops.

**Comment by chrisnorman7** [comment]
So, firstly, if you pick up an object, the ambiance for that object should
stop. If other ambiances are being affected, that is a bug.

Secondly, why can't you create an exit? Is there an error? A traceback? A
crash?

Take care,

Chris Norman

**Comment by shadowpates** [comment]
Hi Chris,
Can you change this ambiance feature? I hate it, because I want to add music to my games.
2. The screenreader don't speak anything, after clicking create exit. The exit don't appear on the map.

3. Please check the ag forum.

**Comment by chrisnorman7** [comment]
Which ambiance feature? That the ambiance for an object stops when it
leaves the room? That seems like common sense to me.

I will do some checks though, to ensure it all works as expected.

I'll have a read over the forum now, although it isn't the place for Earwax
issues honestly.

Take care,

Chris Norman

**Comment by shadowpates** [comment]
No, no this. If i will pick up object, the ambiance stops.
Can you add music playing in the rooms?
And, here's list of ideas from ag forum.
1. New item type. Disposable. This will destroy the item if this will be throwned or used.
2. Ambience for all rooms.
3. Sound for esc key.
4. Walking around the rooms by using arrow keys.
5. Custom shortcuts.
6. Item descriptions.
7. Change log for the earwax story.
8. Readme and change log options for games created with earwax story.

**Comment by chrisnorman7** [comment]
As I've mentioned before, when you pick up an object, the ambiance for that
object intentionally stops. This is because the object is no longer in the
room, but in your inventory.

As for music, just create an ambiance. It acts the same as music.

As for the other stuff, individual issues should be opened for each one,
with far more detail than has been given here.

Take care,

Chris Norman

**Comment by shadowpates** [comment]
How much info you need about the ideas?
Ps. You repaired the exits?

**Comment by chrisnorman7** [comment]
A LORT of information.

And no, because I have literally no idea what problem you're experiencing,
other than "exits aren't working".

All I can do, is try to create an exit on my end (which I will do), and see
what happens.

You've sent me no logs, no command line output, given me very little to
work on.

Take care,

Chris Norman
